export const leaderboard = [
  { refCode: "XZW03", name: "Athul U", score: 7860 },
  { refCode: "PEMAT", name: "Muhammed afsal", score: 4204 },
  { refCode: "U9EI2", name: "Anjitha vinayan", score: 3307 },
  { refCode: "XOVB5", name: "Vian Vinod", score: 3215 },
  { refCode: "RVFI9", name: "Allen Binu", score: 3120 },
  { refCode: "BV83W", name: "Ann S S", score: 3040 },
  { refCode: "NET0J", name: "BAGINESH M B", score: 1710 },
  { refCode: "ZOV6E", name: "Mathson Beshy", score: 1676 },
  { refCode: "42UWP", name: "Akarsha Davis", score: 1525 },
  { refCode: "GAUZ0", name: "Bilal N", score: 1389 },
  { refCode: "E0UW9", name: "Ahammed Sahal A U", score: 1200 },
  { refCode: "C19D5", name: "Sreemaya k rajan", score: 1144 },
  { refCode: "01OLR", name: "Fahmin Fayas. A.K", score: 1142 },
  { refCode: "YS3AD", name: "Shain Shaji", score: 830 },
  { refCode: "PE5JC", name: "Aaliyah Rauf", score: 819 },
  { refCode: "X1YBA", name: "B R KRISHNANUNNI", score: 816 },
  { refCode: "GQW6K", name: "Navaneeth C L", score: 640 },
  { refCode: "4DWXT", name: "Mohammed Ashmil", score: 640 },
  { refCode: "PXKUO", name: "Aleena Rose Antony", score: 340 },
  { refCode: "E792S", name: "Athira V", score: 254 },
  { refCode: "MQVEH", name: "Albert George", score: 223 },
  { refCode: "I9EVG", name: "Juhana sherin T M", score: 205 },
  { refCode: "SP96C", name: "Sithara R S", score: 180 },
  { refCode: "HQVS6", name: "AKSHAY KRISHNA A", score: 177 },
  { refCode: "W51A2", name: "K E NANDAGOPAL", score: 170 },
  { refCode: "Z7DX1", name: "Mohammed Shan", score: 165 },
  { refCode: "2SY4D", name: "sana ranjith", score: 160 },
  { refCode: "9XW3B", name: "Sarah Iype", score: 160 },
  { refCode: "1RPT3", name: "Pranav C P", score: 110 },
  { refCode: "YT35X", name: "KRISHNAPRASAD P", score: 105 },];
