export const leaderboard = [
  { name: "Athul U", refCode: "XZW03", score: 3540 },
  { name: "Anjitha vinayan", refCode: "U9EI2", score: 1844 },
  { name: "Ann S S", refCode: "BV83W", score: 1365 },
  { name: "Akarsha Davis", refCode: "42UWP", score: 1195 },
  { name: "Bilal N", refCode: "GAUZ0", score: 988 },
  { name: "Vian Vinod", refCode: "XOVB5", score: 975 },
  { name: "Mathson Beshy", refCode: "ZOV6E", score: 876 },
  { name: "B R KRISHNANUNNI", refCode: "X1YBA", score: 431 },
  { name: "Aaliyah Rauf", refCode: "PE5JC", score: 419 },
  { name: "Mohammed Shan", refCode: "Z7DX1", score: 155 },
  { name: "Juhana sherin T M", refCode: "I9EVG", score: 120 },
  { name: "Fahmin Fayas. A.K", refCode: "01OLR", score: 108 },
  { name: "Albert George", refCode: "MQVEH", score: 103 },
  { name: "Pranav C P", refCode: "1RPT3", score: 100 },
  { name: "Farhana Fathima Ayoob", refCode: "9NJ64", score: 96 },
  { name: "Anu Anna S", refCode: "32170", score: 95 },
  { name: "Athira V", refCode: "E792S", score: 94 },
  { name: "Ahammed Sahal A U", refCode: "E0UW9", score: 80 },
  { name: "Navaneeth C L", refCode: "GQW6K", score: 80 },
  { name: "Naslu kk", refCode: "9827N", score: 80 },
  { name: "Namitha Manoj", refCode: "QHC76", score: 69 },
  { name: "Alfa K John", refCode: "N432L", score: 65 },
  { name: "Tinu Tomy Netto", refCode: "C4SZM", score: 65 },
  { name: "Muhammed Rashil k", refCode: "PH438", score: 62 },
  { name: "John Varghese Benny", refCode: "N6PFY", score: 51 },
  { name: "KRISHNAPRASAD P", refCode: "YT35X", score: 45 },
  { name: "Amrutha. N", refCode: "T9J0H", score: 40 },
  { name: "Meenakshy jayakumar", refCode: "GWMVF", score: 35 },
  { name: "Kezin B Wilson", refCode: "RGXH0", score: 35 },
  { name: "SALMANUL FARIS P.V", refCode: "A83BW", score: 30 },
];
